[package]
name = "hydro_client"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.3" }
quad-net = "0.1.1"
hydro_common = { path = "../hydro_common" }
bincode = "2.0.0-rc.3"