register_event("start", function()
    pos1 = pos(0, 0, "lobby")
    print(pos1:is_loaded())
    pos1:load()
    print(pos1:is_loaded())
end)

register_event("tick", function()
    print(ticks_passed..":"..seconds_passed)
end)